seq = 'TTTTTTCAATGATATGTGGTGAAAGCCTTGACAATATACCGTGTCAACTCGTTTACGATCGCACTGGTTCAAACGATGGGGCGCTCAGTTGTCCACTACAACGCTATCACGCACTATGAGTGCTTCCATATCCGCTAATGGGAAGCAGTTGCGACCATATCAACCTATCGGGTACTGCGTTTGGAATATTCGCCAACTACGGAAACTATTTGGAATGGGCCTACGCGATTTCAGACGCGCGTCAACCTACTACCTCGAAGTAACACCAGGCTAGATAGTGGTGGCTGTTTTGGAAGGCCCATCTTGAAAGAGAGAAGTAAGACCCAACTCGCCGCGGTAAAATTTTAGAACAGGCAGAAGCCGGGTGGCATTTGACGCTGGCGATAGAGCACTAAGAAAGCCAGGATACGTATTAGTTTGATGCCACCATCCTTACATGGGCGCACGCCTGGGAAGGCCCCTTACAACGGTATGTCATCTGAGACGTTGGCTACATGAAGACTATACTTCGAGGACTTCCTGGTCCAGAGGCTACTGTTAAGAGAGACGGCTCGGGAAAGTTGTGCCTAGACCCTGATACGATGAGCACTGCGAAGACACCCCTCCCATCCCATACTCACGTGTCTGGATCGATCGCCTACCACCTGGCTATTTCAGTGGTAGGTCGGCAGGCGAATAGAGTTGTGATGTACTTGTCAGTTGGGTGGTGGGTGAGCCCGTCGATCTTGAAACCACGTGAATCTAATCCTCCAATCACGCCAATGATACGATGAGGGCGCTGTTGTAATGATCGAGAGTATATCTAGTGGGAGCATGGGGGCTTACTTTATAGCCT'

def nuc_comp(seq):
    a = 0
    c = 0
    t = 0
    g = 0
    for i in seq:
        if i == 'A':
            a = a + 1
        elif i == 'C':
            c = c + 1
        elif i == 'T':
            t = t + 1
        elif i == 'G':
            g = g + 1
    print(a, c, g, t)

nuc_comp(seq)