def motif(seq, motif):
    output = ''
    for i in range(0, len(seq), 1):
        scan = seq[i:i+len(motif)]
        if scan == motif:
            output = output + str(i+1) + ' '
        else:
            pass
    print(output)

#motif('TTGAATCCCAACGCTCGGCAGTTCGCGGCAGTTGGGCAGTTCGGCAGTTCTGAGGAATGGCAGTTTAGGGCAGTTCAGGCAGTTACCATACCGGCAGTTTTGGCAGTTCACGGGCAGTTAGGCAGTTGGCAGTTAAAGCAGGCAGTTGGCAGTTGGCAGTTAGAAGGCAGTTCCGGGCAGTTTGCTCGGCAGTTTACACGCGGCAGTTAGGCAGTTGGCAGTTGGCAGTTTCATGGCAGTTATCGGCGGCAGTTAAAGGGGTGGCAGTTGGCAGTTCGGCCTGGCAGTTGGCAGTTACGGCAGTTCATTTGGCAGTTAGAGGCAGTTAGGCAGTTAGGCAGTTAGGCAGTTACCTAGGCAGTTGACCACGTAATCGTTCAGAGGTTCCGGCAGTTAAGGGCAGTTTAGGGGCAGTTAGGCAGTTTGCAGGCAGTTGGCAGTTCCATGGGCAGTTAAGGCGGCAGTTGGCAGTTAGGCAGTTTCGGCAGTTAGGGGCAGTTGGCAGTTGGCAGTTGGCAGTTGCAGTGGCAGTTCTTCAATGCCAGAAGTGGCAGTTGGCAGTTGAAAAATAGGCAGTTACTGGTTGGCAGTTGGGGCAGTTGCCGGCAGTTTGCAATTGGCAGTTCGGCAGTTTGGCAGTTACTAGGCAGTTGGCAGTTAGGCAGTTGTTGGCAGTTGGCAGTTATGAGAAGGCAGTTAGGCAGTTCGCAGGCAGTTGACGGCAGTTGGCAGTTGGCAGTTAGGCAGTTTGGGCAGTTCTGGCAGTTGGGCAGTTGGCAGTTTGGCAGTTGGCAGTTGCGGCAGTTTTGGCAGTTTCGGGCAGTTTCGGCAGTTCACCGGCAGTTGTGGCAGTTGGGCAGTTGGGCAGTTGGCAGTTGGCAGTTGGGGTCCCGGCAGTTGGCAGTTGGCAGTTTGGGCAGTTAGGCAGTTGGGCAGTTCG', 'GGCAGTTGG')

try:
    data = open('rosalind_subs.txt', 'r')
except ValueError:
    print('eat ass')

seq = data.readline()
thing = data.readline()

motif(seq, thing)