seq = 'GATGGAACTTGACTACGTAAATT'
ros = 'GAGCATTGCAGCGCGGGAGACCGATCACGGGGCATCGACGGGAAACTACCTCTCTCCGGAGGCTTATATCTTGAGATCTGACTCGCTGAGGGGTCAACGTTCGAAGCGGCTGTAGTTAGCGTTGCTATGGTCCACGAGCATTCTATAATATTCTAACCGGTTCGAGTCATCATGCGTTGCCGCGCCGTGGGTTCGGTAACAACCTGGAGATCACGCCCGGCAGCTGAACCAAAAGTCGGCTGAAGGGTCGCCATTTGACTCGGTCCTGGCAGGCACATTTAAACGAGTTGCACTACCAAAACGGCGTTAACCGGCTATTGCGCCCTAGACTCAGCGCGAGGGCCTCTCACATGATTTGGTTTTGGACATAAAGCCTGATTGGTCCATCCGCATATAGAATCGTGAAGTAGCCGACGGTAATCGTGCATGAGCAGGCCCGCCGCGGCGTTAGTGAAGGCAGGCACGGTGTTCTTTGGAGGGATATTACCCATCGTCTGGGTAGATCGAGCTAGTAGTGCAGATCTACGCTTTTGCCCTCCTGGCATTAGCCAGCGAATGATCATTAAATCTACAGTGGAATCGCAAAGCCTTGTGAATATAGCGGGCAAGGTGCCAGACGTACGCGGCGTCTAGGCTTGTTAGTCAGCACGAATCTCTCTGGACTAGAGGAGGCGCTTTAGACAGTTCAGCCTAGCCACTCATGAAATTGCTACCAGGCATGTTACTCGGGTATGGTGTAGGAGATATATTACAGTAACTCGCGAAGGACGTTTTAACACCGTTTGCAGACCTCCGCGCATGTGCTTGACAGAGACTTCGCCGGGGGCAAATCTTAATACGATGGTCAACCGTCGACTGTTCGGCTTCGAAGACTCCGCCGGCTATGTTCCCATTCCTGGC'

def transcribe(seq):
    rna = ""
    for i in seq:
        if i == 'A':
            rna = rna + i
        elif i == 'C':
            rna = rna + i
        elif i == 'T':
            rna = rna + 'U'
        elif i == 'G':
            rna = rna + i
    print(rna)

f = open('rosalind_rna.txt', 'r').read() # .read allows file read as string
transcribe(f)